### ISSUE TITLE
Unable to navigate using arrow keys

### ISSUE THREAD

**Issue by knittingcodemonkey** [deseretdigital/dayzed#2]
Arrow keys are a very nice feature when navigating through something with as many elements as a calendar.

**Comment by mkartchner994** [comment]
Looks like you have addressed this in the examples in https://github.com/deseretdigital/dayzed/pull/4, and I went ahead and merged it. Great work!

Would we want to add this functionality as a part of the dazyed library? Or do we just want to suggest that users implement this in some fashion on their side? I think I would prefer the second option, as the example shows a great way to add it, but leaves it up to the users to implement it in a way that will work best for their situation - Example: maybe down arrow jumps 2 weeks ahead instead of one?

**Comment by knittingcodemonkey** [comment]
I think the arrow key implementation will be determined by the user of the package. Showing them how to implement it should be enough.

**Comment by SimeonC** [comment]
Sorry to resurrect a nearly 4 year old thread, I was recently starting to implement this like in the example and I stumbled across the official spec for aria compatible keyboard navigation here https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html.

In implementing this I have a (soon to be) 300 line onKeyDown handler function + extras, as there's a standard now would you be interested in adding this to the main library now?

I've actually struggled with a couple of things that probably would be easier if it was inside of useDayzed code rather than integrating using the exposed functions, specifically the "next/prev month" interactions; 
* pageDown; same day-ish in next month (or same month next year + shift)
* pageUp; same day-ish in previous month (or same month next year + shift)
* going to prev day which is in last month
* going to next day which is in next month
* going to start of week that is in the previous month
* going to end of week that is in the next month
