### ISSUE TITLE
Fix unnecessary recalculations

### ISSUE THREAD

**Issue by arthurdenner** [deseretdigital/dayzed#40]
The current implementation of `useDayzed` causes new objects, e.g. `calendars`, to be created on every render, even though its params didn't change.

To demonstrate this, I created [this sandbox](https://codesandbox.io/s/dayzed-rerenders-qloll?file=/src/index.js). Update the count and check the logs on the console.
For each render, we get new `calendars`, `getDateProps`, `getBackProps` and `getForwardProps`.

These issues can be solved with memoization and #41 proposes a fix for them.

Please let me know your thoughts around this behaviour and the proposed solution.

**Comment by mkartchner994** [comment]
Thanks for opening this Arthur. This has had me thinking quite a bit. One of my thoughts about this is highlighted in this article pretty nicely - https://kentcdodds.com/blog/usememo-and-usecallback. From the first line:

> Performance optimizations ALWAYS come with a cost but do NOT always come with a benefit.

I think in this case the addition of the `useMemo` and `useCallback` hooks inside of the `useDayzed` hook might fall into that. This is just an assumption, but I would guess for most people using the library the implementation of the `useDayzed` hook is mostly isolated in a component that is focused on receiving props that directly tie to the calendar in some way. So anytime a prop gets passed down the `useMemo` and `useCallback` hooks just become an additional cost instead of a performance optimization as the changed prop would cause those to recalculate the values instead of pulling them from the cache. So I would be a little wary of adding this to the `useDayzed` hook directly as that would be something that everyone using the library would be opted-in to.

That being said, this got me thinking about how we could memoize this and I came to this thought - the biggest thing the `useDayzed` hook is abstracting is the offset state value, but aside from that, the rest of the logic can be converted into a pure function. We could even use the pure function in the `useDayzed` hook itself! I think this could be a nice balance as it still should be backwards compatible but doesn't opt in everyone using the library to those optimizations unessararilsy. For those that really need the optimizations, we can export the pure function and then it can be memoized just like any other function. Here is a [code sandbox](https://codesandbox.io/s/puredayzed-j7pke) with an example.

I'm curios on your thoughts with this approach. Anything I might be missing? I am curious if there is a specific use case you had for this that could help us with talking about any tradeoffs as well.

Thanks!

**Comment by mkartchner994** [comment]
Feel free to reopen this with any feedback you have, but for now I am going to close it. Thanks!
