### ISSUE TITLE
Proper way to show dayzed-powered calendar alongside native date input?

### ISSUE THREAD

**Issue by FezVrasta** [deseretdigital/dayzed#42]
Hi, I'm trying to create a calendar component that shows a `<input type="date" />` along with a custom date picker created by dayzed, the issue is that when I receive the date selected from dayzed and try to assign it to the native input with `<input value={date.toISOString().split('T')[0]} type="date" />` I see a different day.

For example, if I select Sept 1st, it will read `August 31th` in the native picker. I suppose it's an issue with timezones, so now I'm wondering how should I parse the dayzed-provided date so that I get back the correct value to populate the native input element?

**Comment by mkartchner994** [comment]
Hello @FezVrasta! Thanks for the interest in Dayzed. I apologize I have been slow to respond.

I think the issue you are seeing here has to do with the fact that you are stripping out the time from the ISO date string which is important for understanding the date as a whole. As defined in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) for the ISO date string, the timezone is always zero UTC offset. This means depending on what timezone/UTC offset you live in you could get a ISO date string with a date that is different than the date you selected. For example, if you live in Budapest, Hungary (which I believe you do) and you selected January 14, 2021 - the javascript `toISOString()` method would return `2021-01-13T23:00:00.000Z`.

Instead what you would probably want to do is construct the date string using date functions like `getFullYear()`, `getMonth()`, and `getDate()` which will handle the timezone correctly and return the right values. This [codesandbox](https://codesandbox.io/s/dayzed-with-html-input-sm8db?file=/src/Single.js) below has an example of this on line 144.

Since I don't think this is directly an issue with Dayzed, I am going to close this issue. Let me know if there are anymore questions. Thanks!
